---
abstract: 'Log events in a structured manner'
author:
  - "Arthur Axel \"fREW\" Schmidt <frioux+cpan@gmail.com>"
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300028, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Structured
requires:
  Moo: 0
  Test::Deep: 0.88
  Test::Fatal: 0.88
  Test::More: 0.88
  Time::HiRes: 0
  strictures: 0
resources:
  repository: git://github.com/frioux/Log-Structured
version: 0.001002
